[package]
name = "Voxel_Craft_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = "0.59.0"
gl = "*"
image = {version = "*", default-features = false, features = ["png", "rayon"]}
bytemuck = {version = "*", default-features = false}
glam = "*"
noise = "*"
anyhow = "1.0.95"
num = "0.4.3"